git:
 depth: 1
language: node_js
node_js:
- '0.12'
notifications:
  email:
  - supinyo@gmail.com
branches:
  only:
  - master
  - development
script:
- npm install -g grunt-cli
- npm install -g bower
- npm install
- bower install
- git config --global user.email "supinyo@gmail.com"
- git config --global user.name "Supinyo M."
- grunt default if:live if:beta
env:
  global:
    secure: BA4dVZcwJrk0GhUaUcQreHR+xXlvtVEILelPXU/6+FSIe3l/JQWS09r+0NDMDvRr4BIj3MuAte7FGiTzTRvKDi2GKBHYhE7Z8tnBKmm24masTACPC2lht5XnpEatil5b7rwGWv0JrsBE3qSl0GK94X7H5lVLgshhMepg4NhK2hx7tk/17weDXgwXC/J4rzq7de9377LYhmJka2WphD8xUDIYkTSn5PuDGrLZ2gzCn6e13vcd4nn3ZIbTJkyMg2dsxZiVJ+ISagdeZ1DJ5lmnl6l+kH9c/vLfQ8h72AKkLVBn2RmR7Bv9IUDnUV5lhAekRZ9umUKp5paxXrR3thpPfztQoLqETPURqoqOhltxxVFp0N7KjKMJkZGs+eExUmoX4U1T3oe9t8fjA41bLrIJz+dF2v0afxI+fxRZc2O29IHeaFP2FVdY8SEHp+UH3dY89pU3zTo1UyCmalhCDDA8hR5VIq+HdvTTXEUceIegGue/YIr4lRZv98gMx6iSsiOTFHbPLz8N+eBbKEVRLPfIkJX8QWlBFn7r0iuFuBfCUKyvZM9KzH3gKpeQ2VcCTnLqTBM8GiWusv1icHxHQMIX0mKrvdFqkL7bH/RY6GT+7vTsyG7ZumzCS/6DOlaTaiyDAAVx5dJQtd9NAH5MgOrvOX1Z/eRO0kaATyC8Lh/8LIo=
